config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  
  resources :fd_types
  
  get 'admin/user' => 'admin#user'
  get 'admin/fooddrink' => 'admin#fooddrink'
  get 'admin/category' => 'admin#category'
  put 'admin/user/:id' => 'admin#update_user'
  patch 'admin/user/:id' => 'admin#update_user'
  match 'admin/user/:id' => 'admin#destroy_user', via: :delete, as: 'delete_user'
  
  get 'static_pages/:foodtype' => 'static_pages#fd_list', as: 'fd_list'
  

  resources :fd_types
  resources :fooddrinks
  
  mount Commontator::Engine => '/commontator'

  root 'static_pages#home'
  match 'users/profile/:id' => 'users#show', via: :get, as: 'show_user'

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  
  Commontator::Engine.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :threads, :only => [:show] do
    resources :comments, :except => [:index, :destroy], :shallow => true do
      member do
        delete 'delete'
      end
    end
  end
end
  
end

app/views/admin/_category.html.erb
<h1>Categories</h1>
<%= link_to "Add new category", new_fd_type_path %>
<table class="table table-bordered table-hover">
  <thead>
    <thead>
      <tr>
        <th>Food</th>
      </tr>
    </thead>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
    <% if category.foodtype.eql?("food") %>
        <tr>
            <td><%= link_to category.name, fd_type_path(category.id) %></td>
            <td>
                <%= link_to 'Edit', edit_fd_type_path(category.id) %>
                <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
        </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<table class="table table-bordered table-hover">
  <thead>
    <thead>
      <tr>
        <th>Drink</th>
      </tr>
    </thead>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
    <% if category.foodtype.eql?("drink") %>
        <tr>
            <td><%= link_to category.name, fd_type_path(category.id) %></td>
            <td>
                <%= link_to 'Edit', edit_fd_type_path(category.id) %>
                <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
        </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/admin/_fooddrink.html.erb
<h1>Foods/Drinks</h1>
<table class="table table-bordered table-hover">
  <thead>
    <thead>
      <tr>
        <th>Name</th><th>Category</th><th>Created by</th>
      </tr>
    </thead>
  </thead>
  <tbody>
  <% @fooddrinks.each do |fooddrink| %>
    <tr>
        <td><%= link_to fooddrink.name, fooddrink_path(fooddrink.id) %></td>
        <td>
            <%= fooddrink.fd_type.name if fooddrink.fd_type.presence %>
        </td>
        <td><%=link_to fooddrink.user.name, show_user_path(fooddrink.user.id) %></td>
        <td>
            <%= link_to 'Edit', edit_fooddrink_path(fooddrink.id) %>
            <%= link_to 'Destroy', fooddrink, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/_user.html.erb
<h1>Users</h1>
<table class="table table-bordered table-hover">
  <thead>
    <thead>
      <tr>
        <th>Name</th><th>Email</th><th>Role</th>
      </tr>
    </thead>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <% if user.id != current_user.id %>
      <tr>
          <td><%= link_to user.name, show_user_path(user.id) %></td>
        <td><%= user.email %></td>
        <td><%= user.roles.first.name if user.roles.first.presence %></td>
        <td>
          <%= form_tag("/admin/user/" + user.id.to_s, method: :PUT) do %>
              <%= submit_tag is_admin(user) %>
          <% end %>
          <%= button_to "Delete User", delete_user_path(user.id), data: { confirm: "Are you sure?" }, method: :delete %>
        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/admin/category.html.erb
<div class="col-md-9">

<p id="notice"><%= notice %></p>
<h1>Categories</h1>
<%= link_to "Add new category", new_fd_type_path, {:style => 'color: blue;font-weight:bold;text-decoration: underline;'} %>
<table class="table table-bordered table-hover">
  <thead>
    <thead>
      <tr>
        <th>Food (<%= @foods.count %>)</th>
      </tr>
    </thead>
  </thead>
  <tbody>
  <% @foods.each do |category| %>
    <% if category.foodtype.eql?("food") %>
        <tr>
            <td><%= link_to category.name, fd_type_path(category.id) %></td>
            <td>
                <%= link_to 'Edit', edit_fd_type_path(category.id), class: "btn btn-primary" %>
                <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </td>
        </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<table class="table table-bordered table-hover">
  <thead>
    <thead>
      <tr>
        <th>Drink (<%= @drinks.count %>)</th>
      </tr>
    </thead>
  </thead>
  <tbody>
  <% @drinks.each do |category| %>
    <% if category.foodtype.eql?("drink") %>
        <tr>
            <td><%= link_to category.name, fd_type_path(category.id) %></td>
            <td>
                <%= link_to 'Edit', edit_fd_type_path(category.id), class: "btn btn-primary" %>
                <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </td>
        </tr>
    <% end %>
  <% end %>
  </tbody>
</table>
</div>

app/views/admin/fooddrink.html.erb
<p id="notice"><%= notice %></p>
<h1>Foods/Drinks <%= @fooddrinks.count %></h1>
<table class="table table-bordered table-hover">
  <thead>
    <thead>
      <tr>
        <th>Name</th><th>Category</th><th>Created by</th>
      </tr>
    </thead>
  </thead>
  <tbody>
  <% @fooddrinks.each do |fooddrink| %>
    <tr>
        <td><%= link_to fooddrink.name, fooddrink_path(fooddrink.id) %></td>
        <td>
            <%= fooddrink.fd_type.name if fooddrink.fd_type.presence %>
        </td>
        <td><%=link_to fooddrink.user.name, show_user_path(fooddrink.user.id) %></td>
        <td>
            <%= link_to 'Edit', edit_fooddrink_path(fooddrink.id), class: "btn btn-primary" %>
            <%= link_to 'Delete', fooddrink, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'admin/user.html.erb' %>
<%= render 'admin/fooddrink.html.erb' %>
<%= render 'admin/category.html.erb' %>

app/views/admin/user.html.erb
<p id="notice"><%= notice %></p>
<h1>Users (<%= @users.count %>)</h1>
<table class="table table-bordered table-hover">
  <thead>
    <thead>
      <tr>
        <th>Name</th><th>Email</th><th>Role</th>
      </tr>
    </thead>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <% if user.id != current_user.id %>
      <tr>
          <td>
            <i class="entypo-pencil"></i><%= link_to user.name, show_user_path(user.id) %></td>
        <td><%= user.email %></td>
        <td><%= user.roles.first.name if user.roles.first.presence %></td>
        <td style="display:flex;">
          <div class="col-md-6">
          <%= form_tag("/admin/user/" + user.id.to_s, method: :PUT) do %>
              <%= submit_tag is_admin(user), class: "btn btn-primary" %>
          <% end %></div>
          <div class="col-md-6"><%= button_to "Delete User", delete_user_path(user.id), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %>
         </div>
        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>