config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  
  resources :fd_types
  
  get 'admin/user' => 'admin#user'
  get 'admin/fooddrink' => 'admin#fooddrink'
  get 'admin/category' => 'admin#category'
  put 'admin/user/:id' => 'admin#update_user'
  patch 'admin/user/:id' => 'admin#update_user'
  match 'admin/user/:id' => 'admin#destroy_user', via: :delete, as: 'delete_user'
  
  get 'static_pages/:foodtype' => 'static_pages#fd_list', as: 'fd_list'
  

  resources :fd_types
  resources :fooddrinks
  
  mount Commontator::Engine => '/commontator'

  root 'static_pages#home'
  match 'users/profile/:id' => 'users#show', via: :get, as: 'show_user'

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  
  Commontator::Engine.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :threads, :only => [:show] do
    resources :comments, :except => [:index, :destroy], :shallow => true do
      member do
        delete 'delete'
      end
    end
  end
end
  
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-custom">
    <div class="container nav-container">
      <ul class="nav navbar-nav navbar-right">
        <li><%= render 'fooddrinks/fooddrink_search_box.html.erb' %></li>
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
            <% if current_user.has_role? :admin %>
                <li class="dropdown">
                  <a href='#' class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Admin Manage Page
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Manage User", admin_user_path %></li>
                    <li><%= link_to "Manage Food/Drink", admin_fooddrink_path %></li>
                    <li><%= link_to "Manage Category", admin_category_path %></li>
                  </ul>
                </li>
            <% end %>
            <li class="dropdown">
              <a href=<%= show_user_path(current_user.id) %> class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", show_user_path(current_user.id) %></li>
                <li><%= link_to "Add Food/Drink", new_fooddrink_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Change Profile", edit_user_registration_path %></li>
              </ul>
            </li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to "Login/Signup", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_side.html.erb
<div class="sidebar-menu left-side" style="width:250px;">
	  <article class="menu">MENU</article><br>
    
		<div class=" categories sidebar-menu-inner" style="width:100%;">
      
      <ul id="main-menu" class="temp main-menu"  style="font-size: 14px;width:100%;">
       <h3 class="menu-fooddrink"><%= link_to "DRINKS", fd_list_path("drink") %></h3>
        <% @fd_types.each do |type| %>
          <% if type.foodtype=="drink" %>
            <li class="">
              <%= link_to fd_type_path(type.id) do %>
                  <%= type.name %>
              <% end %>
            
          <!--<ul class="">-->
          <!--  <li class=""><a tabindex="-1" href="#">Second level</a></li>-->
          <!--  <li><a href="#">Second level</a></li>-->
          <!--  <li><a href="#">Second level</a></li>-->
          <!--</ul>-->
        </li>
        <% end %>
        <% end %>
      </ul>
      
      <ul  id="main-menu" class="temp main-menu" style="font-size: 14px;width:100%;">
       <h3 class="menu-fooddrink"><%= link_to "FOODS", fd_list_path("food") %></h3>
        <% @fd_types.each do |type| %>
        <% if type.foodtype=="food" %>
            <li class="">
              <%= link_to fd_type_path(type.id) do %>
                  <%= type.name %>
              <% end %>
            </li>
        <% end %>
        <% end %>
      </ul>
      
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>